### ISSUE TITLE
Graylog-plugin-CEF loading Error

### ISSUE THREAD

**Issue by minipop4747** [Graylog2/graylog-plugin-cef#22]
I have stop the graylog service and place the plugin into the plugin directory and restarted the service. But unfortunately I got following error code and the graylog server is not getting up. My Graylog server version is 2.2.2

Need to fix this bug or any method where I can apply CEF plugin into Graylog server input.

[root@graylog ~]# Exception in thread "main" java.lang.NoClassDefFoundError: org/graylog/plugins/pipelineprocessor/a                              st/functions/AbstractFunction
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.net.FactoryURLClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.graylog.plugins.cef.CEFInputModule.configure(CEFInputModule.java:28)
        at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
        at org.graylog2.shared.bindings.PluginBindings.configure(PluginBindings.java:51)
        at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
        at com.google.inject.spi.Elements.getElements(Elements.java:110)
        at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at org.graylog2.shared.bindings.GuiceInjectorHolder.createInjector(GuiceInjectorHolder.java:34)
        at org.graylog2.bootstrap.CmdLineTool.setupInjector(CmdLineTool.java:379)
        at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:193)
        at org.graylog2.bootstrap.Main.main(Main.java:44)
Caused by: java.lang.ClassNotFoundException: org.graylog.plugins.pipelineprocessor.ast.functions.AbstractFunction
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.net.FactoryURLClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 26 more

**Comment by joschi** [comment]
@minipop4747 Either the version of the plugin you've downloaded isn't compatible with the version of Graylog you're using (try https://github.com/Graylog2/graylog-plugin-cef/releases/tag/2.2.0-beta.3) or you're missing the Pipeline Processing plugin in your Graylog setup.

Either way, we are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by minipop4747** [comment]
@joschi ,

I found this issue on when I place this plugin and restart the service. Also I removed this plugin from the plugin directory and restart the service and tested, No issue observed and the graylog perfectly worked. Apart from that I have tested all 2.x.x plugin listed in https://github.com/Graylog2/graylog-plugin-cef/releases, page none of them worked for me and gave same error. So it should be some error in the plugin, not in the graylog.

**Comment by joschi** [comment]
@minipop4747 Please continue this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

If you want help, please include the necessary information, such as the version of Graylog you're using, the version of the plugin you're using, and the complete contents of the logs of your Graylog nodes.
